<a href="https://colab.research.google.com/github/Saurabh703/Deep-Learning/blob/main/Word_Embedding_(Natural_Language_Processing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.preprocessing.text import one_hot

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=['the glass of milk',
      'the glass of ice',
     'I am good person',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of ice',
 'I am good person',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size = 10000

#### One Hot Representation

In [ ]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[5188, 9519, 3887, 7589], [5188, 9519, 3887, 8079], [6054, 3347, 1966, 3413], [6054, 3347, 4456, 1966, 4432], [6655, 5188, 6914, 3887, 9678], [2261, 9286, 3280, 1966]]


### Word Embedding Representation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 5188 9519 3887 7589]
 [   0    0    0    0 5188 9519 3887 8079]
 [   0    0    0    0 6054 3347 1966 3413]
 [   0    0    0 6054 3347 4456 1966 4432]
 [   0    0    0 6655 5188 6914 3887 9678]
 [   0    0    0    0 2261 9286 3280 1966]]


In [ ]:
dim = 15

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 2s 2s/step
[[[ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723
   -0.04530854  0.00050722 -0.04569576 -0.01395905  0.00510569]
  [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723
   -0.04530854  0.00050722 -0.04569576 -0.01395905  0.00510569]
  [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723
   -0.04530854  0.00050722 -0.04569576 -0.01395905  0.00510569]
  [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723
   -0.04530854  0.00050722 -0.04569576 -0.01395905  0.00510569]
  [ 0.02659008  0.02540915 -0.00585405  0.02027677 -0.03353176
   -0.04397931  0.02814107  0.00469636 -0.01252012  0.03003833]
  [ 0.01438311 -0.03806918  0.03390973 -0.0259565  -0.02099068
    0.0332235  -0.03221156  0.03096874 -0.04118339  0.03302458]
  [-0.04015924 -0.03342723 -0.02328488 -0.00506856 -0.01361474
    0.02363838  0.00291996 -0.03944501  0.02636864  0.02318554]
  [ 0.04783477  0.02593533 -0.02793162 -0.00141344  0.00797177
   -0.

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 5188, 9519, 3887, 7589])

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723   -0.04530854
   0.00050722 -0.04569576 -0.01395905  0.00510569]
 [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723   -0.04530854
   0.00050722 -0.04569576 -0.01395905  0.00510569]
 [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723   -0.04530854
   0.00050722 -0.04569576 -0.01395905  0.00510569]
 [ 0.03783679  0.01511839 -0.00911716 -0.0146854  -0.014723   -0.04530854
   0.00050722 -0.04569576 -0.01395905  0.00510569]
 [ 0.02659008  0.02540915 -0.00585405  0.02027677 -0.03353176 -0.04397931
   0.02814107  0.00469636 -0.01252012  0.03003833]
 [ 0.01438311 -0.03806918  0.03390973 -0.0259565  -0.02099068  0.0332235
  -0.03221156  0.03096874 -0.04118339  0.03302458]
 [-0.04015924 -0.03342723 -0.02328488 -0.00506856 -0.01361474  0.02363838
   0.00291996 -0.03944501  0.02636864  0.02318554]
 [ 0.04783477  0.02593533 -0.02793162 -0.00141344  0.00797177 -0.00848939
